### ISSUE TITLE
Mycoviruses

### ISSUE THREAD

**Issue by mfall** [virtool/ref-plant-viruses#7]
Hi, 
thanks a lot for this amazing tool. I am a user of virtool, Virfind and V-pipe and I am planning to have VirAnnot. I can fairly say that I love using virtool. However, there is two improvements  (features) that will be awesom to have  if possible. 
1. When using Pathoscope workflow: Possibility  to retrieve sequences of contigs  from Virtool after a positive detection of a given virus, for further analysis
2. Add more mycoviruses in the reference list (OTUs): For now we only have 4 Sclerotinia mycoviruses and on Botrytis virus X: 

Sclerotinia sclerotiorum mitovirus 3 (SsMV3)
Sclerotinia sclerotiorum mitovirus 4 (SsMV4)
Sclerotinia sclerotiorum hypovirus 1 (SsHV1)
Sclerotinia nivalis mitovirus 2 (SnMV2)
Sclerotinia nivalis mitovirus 1 (SnMV1)
Sclerotinia sclerotiorum dsrna mycovirus (SsDRV)
Botrytis cinerea mitovirus 3 (BcMV3)
Botrytis cinerea mitovirus 1 (BcMV1)
Botrytis cinerea mitovirus 4(BcMV4)
Botryotinia fuckeliana partitivirus 1 (BfPV1)
Botrytis cinerea rna virus 1 (BcRV1)
Sclerotinia sclerotiorum dsrna_mycovirus (SsDRV)
Grapevine associated narnavirus 1 (GaNV1) (plant virus)
Grapevine associated hypovirus 1 (GaHV1)
Botrytis cinerea endornavirus 1 (BcEV1) (in one sample)
FUSARIUM_GRAMINEARUM_DSRNA_MYCOVIRUS-4 (FgDRV)

Thanks a lot!

**Comment by igboyes** [comment]
Thank you for the kind feedback.

1. Please open this as an issue in the [virtool/virtool](https://github.com/virtool/virtool) repository. Our team will have to discuss this as it will add additional processing and complexity to the Pathoscope workflow. Currently, nothing is assembled in this workflow. It is purely based on read mapping.

2. We will be keeping mycoviruses out of the official plant virus reference. For these viruses, I suggest making a reference of your own in Virtool separate from the Plant Viruses reference. You can then run a Pathoscope analyses for each reference.
    In the near future we plan to make more official/remote references available, which your mycovirus reference could serve as a basis for. We are also planning to make it possible to use multiple references in a single run of Pathoscope.
